// frontend/src/gdp/datagen/scene/scene-run-history.tsx
"use client";

import {
  AlertTriangleIcon,
  CheckCircle2Icon,
  ChevronDownIcon,
  ClockIcon,
  Loader2Icon,
  RefreshCwIcon,
  XCircleIcon,
} from "lucide-react";
import { useCallback, useEffect, useState } from "react";
import { toast } from "sonner";

import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { ScrollArea } from "@/components/ui/scroll-area";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { cn } from "@/lib/utils";

import { listSceneRuns, listScenes } from "../common/lib/api";
import type { SceneRunSummary, SceneSummary } from "../common/lib/types";

interface SceneRunHistoryProps {
  onViewRun?: (runId: string, sceneCode: string) => void;
}

export function SceneRunHistory({ onViewRun }: SceneRunHistoryProps) {
  const [runs, setRuns] = useState<SceneRunSummary[]>([]);
  const [scenes, setScenes] = useState<SceneSummary[]>([]);
  const [loading, setLoading] = useState(false);
  const [sceneCode, setSceneCode] = useState<string>("");
  const [status, setStatus] = useState<string>("");
  const [page, setPage] = useState(0);
  const [hasMore, setHasMore] = useState(false);
  const limit = 20;

  // 加载场景列表用于筛选下拉
  useEffect(() => {
    listScenes({ limit: 200, offset: 0 })
      .then(setScenes)
      .catch(() => { /* 忽略 */ });
  }, []);

  const loadRuns = useCallback(async (reset = false) => {
    setLoading(true);
    try {
      const offset = reset ? 0 : page * limit;
      const effectiveSceneCode = sceneCode === "__all__" ? "" : sceneCode;
      const effectiveStatus = status === "__all__" ? "" : status;
      const result = await listSceneRuns({
        sceneCode: effectiveSceneCode || undefined,
        status: effectiveStatus || undefined,
        limit,
        offset,
      });
      if (reset) {
        setRuns(result);
      } else {
        setRuns((prev) => [...prev, ...result]);
      }
      setHasMore(result.length === limit);
      if (reset) setPage(1);
    } catch (error) {
      toast.error(error instanceof Error ? error.message : "加载执行记录失败");
    } finally {
      setLoading(false);
    }
  }, [sceneCode, status, page]);

  // 筛选变化时重置加载
  useEffect(() => {
    void loadRuns(true);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [sceneCode, status]);

  const handleLoadMore = () => {
    setPage((p) => p + 1);
    void loadRuns(false);
  };

  return (
    <div className="flex h-full flex-col bg-background">
      {/* 筛选栏 */}
      <header className="shrink-0 border-b bg-card/50 px-4 py-2.5">
        <div className="flex items-center gap-2">
          <h1 className="text-sm font-semibold mr-4">执行历史</h1>
          <Select value={sceneCode} onValueChange={setSceneCode}>
            <SelectTrigger className="h-7 w-[180px] text-xs">
              <SelectValue placeholder="全部场景" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="__all__" className="text-xs">全部场景</SelectItem>
              {scenes.map((s) => (
                <SelectItem key={s.sceneCode} value={s.sceneCode} className="text-xs">
                  {s.sceneName} ({s.sceneCode})
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
          <Select value={status} onValueChange={setStatus}>
            <SelectTrigger className="h-7 w-[120px] text-xs">
              <SelectValue placeholder="全部状态" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="__all__" className="text-xs">全部状态</SelectItem>
              <SelectItem value="SUCCESS" className="text-xs">成功</SelectItem>
              <SelectItem value="FAILED" className="text-xs">失败</SelectItem>
              <SelectItem value="PARTIAL" className="text-xs">部分成功</SelectItem>
            </SelectContent>
          </Select>
          <Button
            variant="ghost"
            size="icon-sm"
            onClick={() => void loadRuns(true)}
            disabled={loading}
            title="刷新"
          >
            <RefreshCwIcon className={cn("size-3.5", loading && "animate-spin")} />
          </Button>
        </div>
      </header>

      {/* 列表 */}
      <ScrollArea className="flex-1">
        <div className="p-3 space-y-2">
          {runs.length === 0 && !loading && (
            <div className="flex flex-col items-center justify-center py-20 text-muted-foreground">
              <ClockIcon className="size-8 mb-2 opacity-20" />
              <p className="text-sm">暂无执行记录</p>
            </div>
          )}
          {runs.map((run) => (
            <RunCard
              key={run.runId}
              run={run}
              onClick={() => onViewRun?.(run.runId, run.sceneCode)}
            />
          ))}
          {hasMore && (
            <div className="flex justify-center pt-2 pb-4">
              <Button
                variant="outline"
                size="sm"
                onClick={handleLoadMore}
                disabled={loading}
                className="gap-1.5 text-xs"
              >
                {loading ? <Loader2Icon className="size-3 animate-spin" /> : <ChevronDownIcon className="size-3" />}
                加载更多
              </Button>
            </div>
          )}
          {loading && runs.length === 0 && (
            <div className="flex items-center justify-center py-12 text-muted-foreground">
              <Loader2Icon className="size-4 animate-spin mr-2" />
              <span className="text-xs">加载中...</span>
            </div>
          )}
        </div>
      </ScrollArea>
    </div>
  );
}

/* ── 执行记录卡片 ── */

function RunCard({ run, onClick }: { run: SceneRunSummary; onClick: () => void }) {
  const StatusIcon =
    run.status === "SUCCESS"
      ? CheckCircle2Icon
      : run.status === "FAILED"
        ? XCircleIcon
        : AlertTriangleIcon;

  const statusColor =
    run.status === "SUCCESS"
      ? "text-emerald-600 dark:text-emerald-400"
      : run.status === "FAILED"
        ? "text-red-600 dark:text-red-400"
        : "text-amber-600 dark:text-amber-400";

  const borderColor =
    run.status === "SUCCESS"
      ? "border-l-emerald-500"
      : run.status === "FAILED"
        ? "border-l-red-500"
        : "border-l-amber-500";

  const inputsText = Object.keys(run.inputs).length > 0
    ? JSON.stringify(run.inputs)
    : "";

  return (
    <button
      type="button"
      onClick={onClick}
      className={cn(
        "w-full text-left rounded-lg border border-l-4 bg-card p-3 transition-colors",
        "hover:bg-muted/50 hover:shadow-sm cursor-pointer",
        borderColor,
      )}
    >
      {/* 第一行：状态 + 场景 + 版本 + 环境 + 耗时 */}
      <div className="flex items-center gap-2 flex-wrap">
        <StatusIcon className={cn("size-4 shrink-0", statusColor)} />
        <span className="text-sm font-semibold truncate">{run.sceneCode}</span>
        <Badge variant="outline" className="rounded text-[9px] px-1 py-0">v{run.versionNo}</Badge>
        <Badge variant="secondary" className="rounded text-[9px] px-1 py-0">{run.envCode}</Badge>
        <span className="text-[11px] text-muted-foreground flex items-center gap-1">
          <ClockIcon className="size-3" />
          {formatDuration(run.durationMs)}
        </span>
        <span className="ml-auto text-[10px] text-muted-foreground">
          {formatDateTime(run.startedAt)}
        </span>
      </div>

      {/* 第二行：步骤统计 + 入参 */}
      <div className="mt-1.5 flex items-center gap-3 text-[11px] text-muted-foreground">
        <span>
          步骤 <span className="font-medium text-foreground">{run.successCount}/{run.stepCount}</span>
          {run.failedCount > 0 && (
            <span className="text-red-500 ml-1">失败 {run.failedCount}</span>
          )}
        </span>
        {inputsText && (
          <span className="truncate font-mono text-[10px] opacity-70">
            入参: {inputsText}
          </span>
        )}
      </div>

      {/* 错误信息 */}
      {run.errors.length > 0 && (
        <div className="mt-1.5 text-[11px] text-red-600 dark:text-red-400 truncate">
          {run.errors[0]}
        </div>
      )}
    </button>
  );
}

/* ── 工具函数 ── */

function formatDuration(ms: number): string {
  if (!Number.isFinite(ms)) return "-";
  if (ms < 1000) return `${Math.round(ms)}ms`;
  return `${(ms / 1000).toFixed(1)}s`;
}

function formatDateTime(value: string): string {
  if (!value) return "-";
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return "-";
  return date.toLocaleString();
}

// gdpui/src/datagen/views/scene-run-history.vue
<template>
  <div class="run-history">
    <!-- 筛选栏 -->
    <header class="history-header">
      <div class="header-inner">
        <h1 class="header-title">执行历史</h1>
        <el-select v-model="sceneCode" placeholder="全部场景" size="small" class="filter-select" @change="onFilterChange">
          <el-option label="全部场景" value="" />
          <el-option v-for="s in scenes" :key="s.sceneCode" :label="s.sceneName + ' (' + s.sceneCode + ')'" :value="s.sceneCode" />
        </el-select>
        <el-select v-model="status" placeholder="全部状态" size="small" class="filter-select-sm" @change="onFilterChange">
          <el-option label="全部状态" value="" />
          <el-option label="成功" value="SUCCESS" />
          <el-option label="失败" value="FAILED" />
          <el-option label="部分成功" value="PARTIAL" />
        </el-select>
        <el-button size="small" :loading="loading" icon="el-icon-refresh" circle @click="reloadRuns" />
      </div>
    </header>

    <!-- 列表 -->
    <div class="history-list">
      <div v-if="runs.length === 0 && !loading" class="empty-state">
        <font-awesome-icon icon="clock" class="empty-icon" />
        <p>暂无执行记录</p>
      </div>

      <div
        v-for="run in runs"
        :key="run.runId"
        :class="['run-card', `run-card--${run.status.toLowerCase()}`]"
        @click="viewRun(run)"
      >
        <!-- 第一行 -->
        <div class="run-card__header">
          <font-awesome-icon
            :icon="statusIcon(run.status)"
            :class="['status-icon', `status-icon--${run.status.toLowerCase()}`]"
          />
          <span class="run-card__scene">{{ run.sceneCode }}</span>
          <el-tag size="mini" type="info" class="run-card__badge">v{{ run.versionNo }}</el-tag>
          <el-tag size="mini" class="run-card__badge">{{ run.envCode }}</el-tag>
          <span class="run-card__duration">
            <font-awesome-icon icon="clock" />
            {{ formatDuration(run.durationMs) }}
          </span>
          <span class="run-card__time">{{ formatDateTime(run.startedAt) }}</span>
        </div>
        <!-- 第二行 -->
        <div class="run-card__meta">
          <span>
            步骤 <strong>{{ run.successCount }}/{{ run.stepCount }}</strong>
            <span v-if="run.failedCount > 0" class="failed-count">失败 {{ run.failedCount }}</span>
          </span>
          <span v-if="hasInputs(run)" class="run-card__inputs">
            入参: {{ truncateJson(run.inputs) }}
          </span>
        </div>
        <!-- 错误信息 -->
        <div v-if="run.errors.length > 0" class="run-card__error">
          {{ run.errors[0] }}
        </div>
      </div>

      <!-- 加载更多 -->
      <div v-if="hasMore" class="load-more">
        <el-button size="small" :loading="loading" @click="loadMore">
          <font-awesome-icon v-if="!loading" icon="chevron-down" />
          加载更多
        </el-button>
      </div>

      <div v-if="loading && runs.length === 0" class="loading-state">
        <i class="el-icon-loading" />
        <span>加载中...</span>
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import Vue from 'vue'

import { listSceneRuns, listScenes } from '@/datagen/common/lib/api'
import type { SceneRunSummary, SceneSummary } from '@/datagen/common/lib/types'

/**
 * 场景执行历史列表页面。
 * 从 React SceneRunHistory 跨框架重写为 Vue 2 + Element UI。
 */
export default Vue.extend({
  name: 'SceneRunHistory',
  data() {
    return {
      runs: [] as SceneRunSummary[],
      scenes: [] as SceneSummary[],
      loading: false,
      sceneCode: '',
      status: '',
      page: 0,
      hasMore: false,
      limit: 20,
    }
  },
  created() {
    this.loadScenes()
    void this.reloadRuns()
  },
  methods: {
    loadScenes() {
      listScenes({ limit: 200, offset: 0 })
        .then((result) => { this.scenes = result })
        .catch(() => {})
    },
    async reloadRuns() {
      this.page = 0
      this.loading = true
      try {
        const result = await listSceneRuns({
          sceneCode: this.sceneCode || undefined,
          status: this.status || undefined,
          limit: this.limit,
          offset: 0,
        })
        this.runs = result
        this.hasMore = result.length === this.limit
        this.page = 1
      } catch (error) {
        this.$message.error(error instanceof Error ? error.message : '加载执行记录失败')
      } finally {
        this.loading = false
      }
    },
    async loadMore() {
      this.loading = true
      try {
        const result = await listSceneRuns({
          sceneCode: this.sceneCode || undefined,
          status: this.status || undefined,
          limit: this.limit,
          offset: this.page * this.limit,
        })
        this.runs = [...this.runs, ...result]
        this.hasMore = result.length === this.limit
        this.page += 1
      } catch (error) {
        this.$message.error(error instanceof Error ? error.message : '加载更多失败')
      } finally {
        this.loading = false
      }
    },
    onFilterChange() {
      void this.reloadRuns()
    },
    viewRun(run: SceneRunSummary) {
      this.$router.push({
        path: `/datagen/scene/run/${encodeURIComponent(run.sceneCode)}`,
        query: { runId: run.runId },
      }).catch(() => {})
    },
    statusIcon(status: string): string {
      if (status === 'SUCCESS') return 'circle-check'
      if (status === 'FAILED') return 'circle-xmark'
      return 'triangle-exclamation'
    },
    hasInputs(run: SceneRunSummary): boolean {
      return Object.keys(run.inputs).length > 0
    },
    truncateJson(obj: Record<string, unknown>): string {
      const text = JSON.stringify(obj)
      return text.length > 60 ? text.slice(0, 57) + '...' : text
    },
    formatDuration(ms: number): string {
      if (!Number.isFinite(ms)) return '-'
      if (ms < 1000) return `${Math.round(ms)}ms`
      return `${(ms / 1000).toFixed(1)}s`
    },
    formatDateTime(value: string): string {
      if (!value) return '-'
      const d = new Date(value)
      return Number.isNaN(d.getTime()) ? '-' : d.toLocaleString()
    },
  },
})
</script>

<style scoped>
.run-history {
  display: flex;
  flex-direction: column;
  height: 100%;
  background: var(--background);
}

.history-header {
  flex-shrink: 0;
  border-bottom: 1px solid var(--border);
  background: var(--card);
  padding: 10px 16px;
}

.header-inner {
  display: flex;
  align-items: center;
  gap: 8px;
}

.header-title {
  font-size: 14px;
  font-weight: 600;
  margin: 0;
  margin-right: 16px;
  color: var(--foreground);
}

.filter-select {
  width: 200px;
}

.filter-select-sm {
  width: 130px;
}

.history-list {
  flex: 1;
  overflow-y: auto;
  padding: 12px;
}

.empty-state {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  padding: 80px 0;
  color: var(--muted-foreground);
}

.empty-icon {
  font-size: 32px;
  margin-bottom: 8px;
  opacity: 0.2;
}

.empty-state p {
  font-size: 13px;
  margin: 0;
}

.loading-state {
  display: flex;
  align-items: center;
  justify-content: center;
  padding: 48px 0;
  color: var(--muted-foreground);
  font-size: 12px;
  gap: 8px;
}

.run-card {
  width: 100%;
  text-align: left;
  border: 1px solid var(--border);
  border-left: 4px solid var(--border);
  border-radius: 8px;
  background: var(--card);
  padding: 12px;
  margin-bottom: 8px;
  cursor: pointer;
  transition: background 0.15s, box-shadow 0.15s;
}

.run-card:hover {
  background: var(--accent);
  box-shadow: 0 1px 4px rgba(0, 0, 0, 0.06);
}

.run-card--success {
  border-left-color: #10b981;
}

.run-card--failed {
  border-left-color: #ef4444;
}

.run-card--partial {
  border-left-color: #f59e0b;
}

.run-card__header {
  display: flex;
  align-items: center;
  gap: 8px;
  flex-wrap: wrap;
}

.status-icon {
  font-size: 16px;
  flex-shrink: 0;
}

.status-icon--success {
  color: #10b981;
}

.status-icon--failed {
  color: #ef4444;
}

.status-icon--partial {
  color: #f59e0b;
}

.run-card__scene {
  font-size: 14px;
  font-weight: 600;
  color: var(--foreground);
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.run-card__badge {
  flex-shrink: 0;
}

.run-card__duration {
  font-size: 11px;
  color: var(--muted-foreground);
  display: flex;
  align-items: center;
  gap: 4px;
}

.run-card__time {
  margin-left: auto;
  font-size: 10px;
  color: var(--muted-foreground);
}

.run-card__meta {
  display: flex;
  align-items: center;
  gap: 12px;
  margin-top: 6px;
  font-size: 11px;
  color: var(--muted-foreground);
}

.failed-count {
  color: #ef4444;
  margin-left: 4px;
}

.run-card__inputs {
  font-family: ui-monospace, SFMono-Regular, Menlo, monospace;
  font-size: 10px;
  opacity: 0.7;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
  max-width: 300px;
}

.run-card__error {
  margin-top: 6px;
  font-size: 11px;
  color: #ef4444;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.load-more {
  display: flex;
  justify-content: center;
  padding: 8px 0 16px;
}
</style>
