// gdpui/src/datagen/components/http-output-extraction-editor.vue
<template>
  <section class="output-extraction">
    <div class="oe-trigger" @click="open = !open">
      <font-awesome-icon :icon="open ? 'chevron-down' : 'chevron-right'" class="oe-chevron" />
      <span>提取响应数据到变量</span>
      <span v-if="count > 0" class="oe-count">{{ count }}</span>
    </div>

    <div v-show="open" class="oe-body">
      <p class="oe-hint">
        从 Body / Headers / Cookies 中提取字段，定义下游步骤可引用的变量名。
      </p>

      <div :class="{ 'oe-disabled': disabled }">
        <div class="oe-table">
          <div class="oe-table-head">
            <div>来源</div>
            <div>响应字段</div>
            <div>下游变量名</div>
            <div>中文名</div>
            <div>备注</div>
            <div class="oe-center">操作</div>
          </div>

          <div class="oe-table-body">
            <div
              v-for="row in mappingRows"
              :key="row.varName"
              class="oe-row"
              :class="{ 'oe-row--incomplete': row.missingLabel || row.missingRemark }"
            >
              <div class="oe-center">
                <span class="oe-source" :class="'oe-source--' + row.source.toLowerCase()">
                  {{ row.source }}
                </span>
              </div>
              <div class="oe-field" :title="row.path">{{ row.fieldName }}</div>
              <div class="oe-varname">
                <span class="oe-eq">=</span>
                <el-input
                  :value="row.varName"
                  size="small"
                  placeholder="输入变量名"
                  class="oe-mono"
                  @input="renameVar(row.varName, $event)"
                />
              </div>
              <el-input
                :value="row.label"
                size="small"
                placeholder="中文名"
                :class="{ 'oe-warn': row.missingLabel }"
                @input="updateMeta(row.varName, 'label', $event)"
              />
              <el-input
                :value="row.remark"
                size="small"
                placeholder="业务说明"
                :class="{ 'oe-warn': row.missingRemark }"
                @input="updateMeta(row.varName, 'remark', $event)"
              />
              <div class="oe-center">
                <el-button type="text" class="oe-del" @click="pendingDeleteKey = row.varName">
                  <font-awesome-icon icon="trash" />
                </el-button>
              </div>
            </div>

            <div v-if="mappingRows.length === 0" class="oe-empty">
              未配置提取项，在下方选择字段添加
            </div>
          </div>
        </div>

        <!-- 快速添加下拉 -->
        <div class="oe-quickadd">
          <el-select
            v-if="extractableBodyFields.length > 0"
            :value="''"
            size="small"
            placeholder="+ Body 字段"
            class="oe-add-select"
            @change="addBodyField"
          >
            <el-option
              v-for="f in extractableBodyFields"
              :key="f.path"
              :label="f.label"
              :value="f.path"
            />
          </el-select>

          <el-select
            v-if="headerExtractable.length > 0"
            :value="''"
            size="small"
            placeholder="+ Header"
            class="oe-add-select"
            @change="addHeaderField"
          >
            <el-option
              v-for="h in headerExtractable"
              :key="h.name"
              :label="h.label ? `${h.name} (${h.label})` : h.name"
              :value="h.name"
            />
          </el-select>

          <el-select
            v-if="cookieExtractable.length > 0"
            :value="''"
            size="small"
            placeholder="+ Cookie"
            class="oe-add-select"
            @change="addCookieField"
          >
            <el-option
              v-for="c in cookieExtractable"
              :key="c.name"
              :label="c.label ? `${c.name} (${c.label})` : c.name"
              :value="c.name"
            />
          </el-select>
        </div>
      </div>
    </div>

    <confirm-dialog
      :open="pendingDeleteKey !== null"
      title="删除提取项"
      :description="`确定删除提取项 &quot;${pendingDeleteKey}&quot; 吗？`"
      @update:open="onDialogOpenChange"
      @confirm="handleDelete"
    />
  </section>
</template>

<script lang="ts">
import Vue, { type PropType } from 'vue'

import { flattenSchema, type FlatSchemaEntry } from '@/datagen/common/lib/schema-utils'
import type { HttpStepDefinition, InputFieldDefinition } from '@/datagen/common/lib/types'
import {
  bodyExpression,
  cookieExpression,
  headerExpression,
  isSameMapping,
  mappingDisplayName,
  mappingSource,
} from '@/datagen/common/lib/extraction-expression'

import ConfirmDialog from './confirm-dialog.vue'

interface OutputMeta {
  label?: string
  remark?: string
}

interface MappingRow {
  varName: string
  path: string
  source: 'Body' | 'Headers' | 'Cookies'
  fieldName: string
  label: string
  remark: string
  missingLabel: boolean
  missingRemark: boolean
}

/**
 * 响应数据提取编辑器（合并了 React 的 Section + Editor 两个导出）。
 *
 * Ported from `http-output-extraction-editor.tsx`. Maps response Body/Header/
 * Cookie fields to downstream variable names with optional 中文名/备注 metadata.
 * Emits `change` with `Partial<HttpStepDefinition>` (outputMapping/outputMeta),
 * matching the source's onChange contract.
 */
export default Vue.extend({
  name: 'HttpOutputExtractionSection',
  components: { ConfirmDialog },
  props: {
    step: { type: Object as PropType<HttpStepDefinition>, required: true },
    disabled: { type: Boolean, default: false },
  },
  data() {
    return {
      open: true,
      pendingDeleteKey: null as string | null,
    }
  },
  computed: {
    outputMapping(): Record<string, string> {
      return this.step.outputMapping ?? {}
    },
    count(): number {
      return Object.keys(this.outputMapping).length
    },
    schema(): InputFieldDefinition[] {
      return this.step.responseSchema ?? []
    },
    headersSchema(): InputFieldDefinition[] {
      return this.step.responseHeadersSchema ?? []
    },
    cookiesSchema(): InputFieldDefinition[] {
      return this.step.responseCookiesSchema ?? []
    },
    bodyFlatFields(): FlatSchemaEntry[] {
      return flattenSchema(this.schema, '$')
    },
    extractableBodyFields(): FlatSchemaEntry[] {
      return this.bodyFlatFields.filter((f) => f.type !== 'object' && f.type !== 'array')
    },
    headerExtractable(): InputFieldDefinition[] {
      return this.headersSchema.filter((h) => h.type !== 'object' && h.type !== 'array')
    },
    cookieExtractable(): InputFieldDefinition[] {
      return this.cookiesSchema.filter((c) => c.type !== 'object' && c.type !== 'array')
    },
    mappingRows(): MappingRow[] {
      const meta = this.step.outputMeta ?? {}
      return Object.entries(this.outputMapping).map(([varName, path]) => {
        const source = mappingSource(path)
        const matched = this.bodyFlatFields.find((f) => isSameMapping(bodyExpression(f.path), path))
        const m: OutputMeta = meta[varName] ?? {}
        return {
          varName,
          path,
          source,
          fieldName: matched ? matched.label : mappingDisplayName(path),
          label: m.label ?? '',
          remark: m.remark ?? '',
          missingLabel: !(m.label ?? '').trim(),
          missingRemark: !(m.remark ?? '').trim(),
        }
      })
    },
  },
  methods: {
    renameVar(oldName: string, newName: string) {
      if (newName === oldName) return
      const next: Record<string, string> = {}
      const nextMeta = { ...(this.step.outputMeta ?? {}) }
      Object.entries(this.outputMapping).forEach(([k, v]) => {
        const targetKey = k === oldName ? newName : k
        next[targetKey] = v
        if (k === oldName) {
          nextMeta[targetKey] = nextMeta[oldName] ?? {}
          delete nextMeta[oldName]
        }
      })
      this.$emit('change', { outputMapping: next, outputMeta: nextMeta })
    },
    updateMeta(varName: string, field: 'label' | 'remark', value: string) {
      const nextMeta = { ...(this.step.outputMeta ?? {}) }
      nextMeta[varName] = { ...nextMeta[varName], [field]: value }
      this.$emit('change', { outputMeta: nextMeta })
    },
    /** 确认对话框关闭时清空待删除键 */
    onDialogOpenChange(o: boolean) {
      if (!o) this.pendingDeleteKey = null
    },
    handleDelete() {
      const key = this.pendingDeleteKey
      if (!key) return
      const next = { ...this.outputMapping }
      const nextMeta = { ...(this.step.outputMeta ?? {}) }
      delete next[key]
      delete nextMeta[key]
      this.$emit('change', { outputMapping: next, outputMeta: nextMeta })
      this.pendingDeleteKey = null
    },
    uniqueName(base: string): string {
      let varName = base
      let suffix = 1
      while (varName in this.outputMapping) {
        varName = `${base}_${suffix++}`
      }
      return varName
    },
    addBodyField(path: string) {
      if (!path) return
      const base = path.split('.').pop()?.replace('[*]', '') ?? 'data'
      const varName = this.uniqueName(base)
      const matchedField = this.bodyFlatFields.find((f) => f.path === path)
      const nextMeta = { ...(this.step.outputMeta ?? {}) }
      nextMeta[varName] = {
        label: matchedField?.fieldLabel ?? '',
        remark: matchedField?.fieldRemark ?? '',
      }
      this.$emit('change', {
        outputMapping: { ...this.outputMapping, [varName]: bodyExpression(path) },
        outputMeta: nextMeta,
      })
    },
    addHeaderField(name: string) {
      if (!name) return
      const base = name.replace(/-/g, '_').toLowerCase()
      const varName = this.uniqueName(base)
      const header = this.headersSchema.find((h) => h.name === name)
      const nextMeta = { ...(this.step.outputMeta ?? {}) }
      nextMeta[varName] = { label: header?.label ?? '', remark: header?.remark ?? '' }
      this.$emit('change', {
        outputMapping: { ...this.outputMapping, [varName]: headerExpression(name) },
        outputMeta: nextMeta,
      })
    },
    addCookieField(name: string) {
      if (!name) return
      const varName = this.uniqueName(name)
      const cookie = this.cookiesSchema.find((c) => c.name === name)
      const nextMeta = { ...(this.step.outputMeta ?? {}) }
      nextMeta[varName] = { label: cookie?.label ?? '', remark: cookie?.remark ?? '' }
      this.$emit('change', {
        outputMapping: { ...this.outputMapping, [varName]: cookieExpression(name) },
        outputMeta: nextMeta,
      })
    },
  },
})
</script>

<style scoped>
.output-extraction {
  display: flex;
  flex-direction: column;
}

.oe-trigger {
  display: flex;
  align-items: center;
  gap: 8px;
  width: 100%;
  padding: 8px 0;
  border-bottom: 1px solid var(--border);
  font-size: 14px;
  font-weight: 700;
  color: #2563eb;
  cursor: pointer;
}

.oe-chevron {
  font-size: 13px;
}

.oe-count {
  margin-left: 4px;
  border-radius: 9999px;
  background-color: var(--muted);
  padding: 0 6px;
  font-size: 9px;
  font-weight: 700;
  color: var(--muted-foreground);
}

.oe-body {
  display: flex;
  flex-direction: column;
  gap: 12px;
  padding-top: 12px;
}

.oe-hint {
  margin: 0;
  font-size: 12px;
  color: var(--muted-foreground);
}

.oe-disabled {
  pointer-events: none;
  opacity: 0.5;
}

.oe-table {
  border: 1px solid var(--border);
  border-radius: 8px;
  background-color: var(--card);
  overflow: hidden;
}

.oe-table-head,
.oe-row {
  display: grid;
  grid-template-columns: 72px minmax(120px, 1fr) minmax(120px, 1fr) 110px minmax(140px, 1fr) 40px;
  gap: 8px;
  align-items: center;
}

.oe-table-head {
  padding: 8px 12px;
  background-color: var(--muted);
  font-size: 10px;
  font-weight: 700;
  text-transform: uppercase;
  color: var(--muted-foreground);
  border-bottom: 1px solid var(--border);
}

.oe-table-body {
  padding: 6px;
  display: flex;
  flex-direction: column;
  gap: 6px;
}

.oe-row {
  padding: 4px 12px;
  border-radius: 4px;
  border: 1px solid transparent;
}

.oe-row:hover {
  border-color: var(--border);
}

.oe-row--incomplete {
  border-left: 2px solid #fbbf24;
}

.oe-center {
  display: flex;
  justify-content: center;
}

.oe-source {
  font-size: 9px;
  font-weight: 700;
  padding: 1px 6px;
  border-radius: 4px;
}

.oe-source--body {
  background-color: rgba(16, 185, 129, 0.1);
  color: #059669;
}

.oe-source--headers {
  background-color: rgba(59, 130, 246, 0.1);
  color: #2563eb;
}

.oe-source--cookies {
  background-color: rgba(245, 158, 11, 0.1);
  color: #d97706;
}

.oe-field {
  font-size: 12px;
  font-family: ui-monospace, SFMono-Regular, Menlo, monospace;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.oe-varname {
  display: flex;
  align-items: center;
  gap: 8px;
}

.oe-eq {
  font-size: 10px;
  color: var(--muted-foreground);
}

.oe-mono >>> .el-input__inner {
  font-family: ui-monospace, SFMono-Regular, Menlo, monospace;
}

.oe-warn >>> .el-input__inner {
  border-left: 2px solid #fbbf24;
}

.oe-del {
  color: var(--muted-foreground);
  padding: 4px;
}

.oe-del:hover {
  color: var(--destructive);
}

.oe-empty {
  padding: 16px;
  text-align: center;
  font-size: 10px;
  font-style: italic;
  color: var(--muted-foreground);
}

.oe-quickadd {
  display: flex;
  gap: 8px;
}

.oe-add-select {
  width: 180px;
}
</style>

// frontend/src/gdp/datagen/common/source-forms/http-output-extraction-editor.tsx
"use client";

import {
  ChevronDownIcon,
  ChevronRightIcon,
  PlusIcon,
  Trash2Icon,
} from "lucide-react";
import { useMemo, useState } from "react";

import { Button } from "@/components/ui/button";
import {
  Collapsible,
  CollapsibleContent,
  CollapsibleTrigger,
} from "@/components/ui/collapsible";
import { Input } from "@/components/ui/input";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { cn } from "@/lib/utils";

import { flattenSchema } from "../lib/schema-utils";
import type { HttpStepDefinition } from "../lib/types";
import { ConfirmDialog } from "../ui/confirm-dialog";

/* ── 表达式辅助函数（与 http-response-mapping-editor 共享） ── */

const EXPRESSION_RE = /^\$\{([A-Z_]+)\((.*)\)\}$/;

export function extractorExpression(source: string, path: string) {
  return `\${${source}(${path})}`;
}

export function bodyExpression(path: string) {
  return extractorExpression("RES_BODY", expressionPath(path));
}

export function headerExpression(name: string) {
  return extractorExpression("RES_HEADER", name);
}

export function cookieExpression(name: string) {
  return extractorExpression("RES_COOKIE", name);
}

export function expressionPath(path: string) {
  return path.replace(/^\$\.?/, "");
}

export function parseExtractor(value: string): { source: string; path: string } | null {
  const match = EXPRESSION_RE.exec(value.trim());
  if (!match) return null;
  return { source: match[1] ?? "", path: match[2] ?? "" };
}

export function mappingSource(value: string): "Body" | "Headers" | "Cookies" {
  const parsed = parseExtractor(value);
  if (parsed?.source === "RES_HEADER") return "Headers";
  if (parsed?.source === "RES_COOKIE") return "Cookies";
  return "Body";
}

export function mappingDisplayName(value: string) {
  const parsed = parseExtractor(value);
  if (parsed) return parsed.path.split(".").pop()?.replace("[*]", "") ?? parsed.path;
  return value.split(".").pop()?.replace("[*]", "") ?? value;
}

export function normalizeMapping(value: string) {
  const parsed = parseExtractor(value);
  if (parsed) {
    return `${parsed.source}:${parsed.source === "RES_HEADER" ? parsed.path.toLowerCase() : parsed.path}`;
  }
  return `INVALID:${value}`;
}

export function isSameMapping(a: string, b: string) {
  return normalizeMapping(a) === normalizeMapping(b);
}

/* ── 组件 ── */

interface HttpOutputExtractionEditorProps {
  step: HttpStepDefinition;
  onChange: (updates: Partial<HttpStepDefinition>) => void;
  disabled?: boolean;
  showHeader?: boolean;
}

export function HttpOutputExtractionSection({
  step,
  onChange,
  disabled = false,
}: Omit<HttpOutputExtractionEditorProps, "showHeader">) {
  const count = Object.keys(step.outputMapping ?? {}).length;
  const [open, setOpen] = useState(true);

  return (
    <Collapsible open={open} onOpenChange={setOpen}>
      <CollapsibleTrigger className="flex items-center gap-2 w-full py-2 border-b text-sm font-bold text-blue-600 hover:text-blue-700 transition-colors">
        {open ? (
          <ChevronDownIcon className="size-4" />
        ) : (
          <ChevronRightIcon className="size-4" />
        )}
        提取响应数据到变量
        {count > 0 && (
          <span className="ml-1 rounded-full bg-muted px-1.5 text-[9px] font-bold text-muted-foreground">
            {count}
          </span>
        )}
      </CollapsibleTrigger>

      <CollapsibleContent className="space-y-3 pt-3">
        <p className="text-xs text-muted-foreground">
          从 Body / Headers / Cookies 中提取字段，定义下游步骤可引用的变量名。
        </p>
        <HttpOutputExtractionEditor
          step={step}
          onChange={onChange}
          disabled={disabled}
          showHeader={false}
        />
      </CollapsibleContent>
    </Collapsible>
  );
}

export function HttpOutputExtractionEditor({
  step,
  onChange,
  disabled = false,
  showHeader = true,
}: HttpOutputExtractionEditorProps) {
  const [pendingDeleteKey, setPendingDeleteKey] = useState<string | null>(null);

  const outputMapping = step.outputMapping ?? {};
  const schema = useMemo(() => step.responseSchema ?? [], [step.responseSchema]);
  const headersSchema = useMemo(() => step.responseHeadersSchema ?? [], [step.responseHeadersSchema]);
  const cookiesSchema = useMemo(() => step.responseCookiesSchema ?? [], [step.responseCookiesSchema]);

  /* ── 展开后的字段列表 ── */
  const bodyFlatFields = useMemo(() => flattenSchema(schema, "$"), [schema]);
  const extractableBodyFields = useMemo(
    () => bodyFlatFields.filter((f) => f.type !== "object" && f.type !== "array"),
    [bodyFlatFields],
  );
  const headerExtractable = useMemo(
    () => headersSchema.filter((h) => h.type !== "object" && h.type !== "array"),
    [headersSchema],
  );
  const cookieExtractable = useMemo(
    () => cookiesSchema.filter((c) => c.type !== "object" && c.type !== "array"),
    [cookiesSchema],
  );

  const handleDelete = () => {
    if (!pendingDeleteKey) return;
    const next = { ...outputMapping };
    const nextMeta = { ...(step.outputMeta ?? {}) };
    delete next[pendingDeleteKey];
    delete nextMeta[pendingDeleteKey];
    onChange({ outputMapping: next, outputMeta: nextMeta });
    setPendingDeleteKey(null);
  };

  return (
    <section className="space-y-3">
      {showHeader && (
        <>
          <div className="flex items-center justify-between border-b pb-2">
            <div className="flex items-center gap-2 text-blue-600 font-bold text-sm">
              <span>提取响应数据到变量</span>
            </div>
          </div>
          <p className="text-xs text-muted-foreground">
            从 Body / Headers / Cookies 中提取字段，定义下游步骤可引用的变量名。
          </p>
        </>
      )}
      <div className={cn("space-y-2", disabled && "pointer-events-none opacity-50")}>
        <div className="rounded-lg border bg-card overflow-hidden">
          <div className="grid grid-cols-[72px_minmax(120px,1fr)_minmax(120px,1fr)_110px_minmax(140px,1fr)_40px] gap-2 px-3 py-2 bg-muted/40 text-[10px] font-bold text-muted-foreground uppercase border-b">
            <div>来源</div>
            <div>响应字段</div>
            <div>下游变量名</div>
            <div>中文名</div>
            <div>备注</div>
            <div className="text-center">操作</div>
          </div>
          <div className="p-1.5 space-y-1.5">
            {Object.entries(outputMapping).map(([varName, path]) => {
              const source = mappingSource(path);
              const sourceColor =
                source === "Body"
                  ? "bg-emerald-500/10 text-emerald-600"
                  : source === "Headers"
                    ? "bg-blue-500/10 text-blue-600"
                    : "bg-amber-500/10 text-amber-600";

              const matched = bodyFlatFields.find((f) => isSameMapping(bodyExpression(f.path), path));
              const meta = step.outputMeta?.[varName] ?? {};
              const missingLabel = !(meta.label ?? "").trim();
              const missingRemark = !(meta.remark ?? "").trim();

              return (
                <div
                  key={varName}
                  className={cn(
                    "grid grid-cols-[72px_minmax(120px,1fr)_minmax(120px,1fr)_110px_minmax(140px,1fr)_40px] gap-2 px-3 items-center bg-muted/10 p-1 rounded border border-transparent hover:border-border transition-all",
                    (missingLabel || missingRemark) && "bg-amber-50/35 border-amber-200",
                  )}
                >
                  <div className="flex justify-center">
                    <span className={cn("text-[9px] font-bold px-1.5 py-0.5 rounded", sourceColor)}>
                      {source}
                    </span>
                  </div>
                  <div className="px-2 text-xs truncate font-mono" title={path}>
                    {matched ? matched.label : mappingDisplayName(path)}
                  </div>
                  <div className="flex items-center gap-2">
                    <span className="text-[10px] text-muted-foreground shrink-0">=</span>
                    <Input
                      className="h-7 text-xs font-mono bg-background"
                      value={varName}
                      placeholder="输入变量名"
                      onChange={(e) => {
                        const newName = e.target.value;
                        if (newName === varName) return;
                        const next: Record<string, string> = {};
                        const nextMeta = { ...(step.outputMeta ?? {}) };
                        Object.entries(outputMapping).forEach(([k, v]) => {
                          const targetKey = k === varName ? newName : k;
                          next[targetKey] = v;
                          if (k === varName) {
                            nextMeta[targetKey] = nextMeta[varName] ?? {};
                            delete nextMeta[varName];
                          }
                        });
                        onChange({ outputMapping: next, outputMeta: nextMeta });
                      }}
                    />
                  </div>
                  <Input
                    className={cn(
                      "h-7 text-xs bg-background",
                      missingLabel && "border-amber-400 bg-amber-50/40",
                    )}
                    value={meta.label ?? ""}
                    placeholder="中文名"
                    onChange={(e) => {
                      const nextMeta = { ...(step.outputMeta ?? {}) };
                      nextMeta[varName] = { ...nextMeta[varName], label: e.target.value };
                      onChange({ outputMeta: nextMeta });
                    }}
                  />
                  <Input
                    className={cn(
                      "h-7 text-xs bg-background",
                      missingRemark && "border-amber-400 bg-amber-50/40",
                    )}
                    value={meta.remark ?? ""}
                    placeholder="业务说明"
                    onChange={(e) => {
                      const nextMeta = { ...(step.outputMeta ?? {}) };
                      nextMeta[varName] = { ...nextMeta[varName], remark: e.target.value };
                      onChange({ outputMeta: nextMeta });
                    }}
                  />
                  <div className="flex justify-center">
                    <Button
                      variant="ghost"
                      size="sm"
                      className="h-6 w-6 text-muted-foreground hover:text-destructive"
                      onClick={() => setPendingDeleteKey(varName)}
                    >
                      <Trash2Icon className="size-3" />
                    </Button>
                  </div>
                </div>
              );
            })}
            {Object.keys(outputMapping).length === 0 && (
              <div className="py-4 text-center text-[10px] text-muted-foreground italic">
                未配置提取项，在上方各页签中勾选字段或点击下方按钮添加
              </div>
            )}
          </div>
        </div>

        {/* 快速添加下拉菜单 */}
        <div className="flex gap-2">
          {extractableBodyFields.length > 0 && (
            <Select onValueChange={(path) => {
              if (!path) return;
              const baseName = path.split(".").pop()?.replace("[*]", "") ?? "data";
              let varName = baseName;
              let suffix = 1;
              while (varName in outputMapping) {
                varName = `${baseName}_${suffix++}`;
              }
              const matchedField = bodyFlatFields.find((f) => f.path === path);
              const expression = bodyExpression(path);
              const nextMeta = { ...(step.outputMeta ?? {}) };
              nextMeta[varName] = {
                label: matchedField?.fieldLabel ?? "",
                remark: matchedField?.fieldRemark ?? "",
              };
              onChange({
                outputMapping: { ...outputMapping, [varName]: expression },
                outputMeta: nextMeta,
              });
            }}>
              <SelectTrigger className="w-[180px] h-8 text-xs gap-2">
                <PlusIcon className="size-3" />
                <SelectValue placeholder="+ Body 字段" />
              </SelectTrigger>
              <SelectContent>
                {extractableBodyFields.map((f) => (
                    <SelectItem key={f.path} value={f.path} className="text-xs">
                      {f.label}
                    </SelectItem>
                ))}
              </SelectContent>
            </Select>
          )}
          {headerExtractable.length > 0 && (
            <Select onValueChange={(name) => {
              if (!name) return;
              const path = headerExpression(name);
              let varName = name.replace(/-/g, "_").toLowerCase();
              let suffix = 1;
              while (varName in outputMapping) {
                varName = `${name.replace(/-/g, "_").toLowerCase()}_${suffix++}`;
              }
              const header = headersSchema.find((h) => h.name === name);
              const nextMeta = { ...(step.outputMeta ?? {}) };
              nextMeta[varName] = { label: header?.label ?? "", remark: header?.remark ?? "" };
              onChange({
                outputMapping: { ...outputMapping, [varName]: path },
                outputMeta: nextMeta,
              });
            }}>
              <SelectTrigger className="w-[180px] h-8 text-xs gap-2">
                <PlusIcon className="size-3" />
                <SelectValue placeholder="+ Header" />
              </SelectTrigger>
              <SelectContent>
                {headerExtractable.map((h) => (
                  <SelectItem key={h.name} value={h.name} className="text-xs">
                    {h.name} {h.label ? `(${h.label})` : ""}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          )}
          {cookieExtractable.length > 0 && (
            <Select onValueChange={(name) => {
              if (!name) return;
              const path = cookieExpression(name);
              let varName = name;
              let suffix = 1;
              while (varName in outputMapping) {
                varName = `${name}_${suffix++}`;
              }
              const cookie = cookiesSchema.find((c) => c.name === name);
              const nextMeta = { ...(step.outputMeta ?? {}) };
              nextMeta[varName] = { label: cookie?.label ?? "", remark: cookie?.remark ?? "" };
              onChange({
                outputMapping: { ...outputMapping, [varName]: path },
                outputMeta: nextMeta,
              });
            }}>
              <SelectTrigger className="w-[180px] h-8 text-xs gap-2">
                <PlusIcon className="size-3" />
                <SelectValue placeholder="+ Cookie" />
              </SelectTrigger>
              <SelectContent>
                {cookieExtractable.map((c) => (
                  <SelectItem key={c.name} value={c.name} className="text-xs">
                    {c.name} {c.label ? `(${c.label})` : ""}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          )}
        </div>
      </div>

      <ConfirmDialog
        open={pendingDeleteKey !== null}
        onOpenChange={(open) => { if (!open) setPendingDeleteKey(null); }}
        onConfirm={handleDelete}
        title="删除提取项"
        description={`确定删除提取项 "${pendingDeleteKey}" 吗？`}
      />
    </section>
  );
}
