// gdpui/src/datagen/views/task-editor.vue
<template>
  <div class="task-editor">
    <!-- 头部 -->
    <div class="editor-header">
      <div class="header-left">
        <el-button type="text" icon="el-icon-arrow-left" @click="goBack" />
        <div>
          <h2 class="header-title">{{ headerTitle }}</h2>
          <p class="header-sub">
            {{ task.taskName || '未命名任务' }}
            <span v-if="persistedCode" class="header-code">({{ persistedCode }})</span>
          </p>
        </div>
      </div>
      <div class="header-actions">
        <el-button
          v-if="persistedCode && task.status === 'PUBLISHED' && !readOnly"
          size="small"
          plain
          @click="openRunDialog"
        >
          <font-awesome-icon icon="play" class="play-icon" /> 执行
        </el-button>
        <template v-if="!readOnly">
          <el-button size="small" plain :loading="validating" @click="handleValidate">
            <font-awesome-icon v-if="!validating" icon="check-double" /> 校验
          </el-button>
          <el-button size="small" plain :loading="saving" @click="save">
            <font-awesome-icon v-if="!saving" icon="floppy-disk" /> 保存
          </el-button>
          <el-button size="small" type="primary" :loading="publishing" @click="handlePublish">
            <font-awesome-icon v-if="!publishing" icon="paper-plane" /> 发布
          </el-button>
        </template>
      </div>
    </div>

    <!-- 校验问题 -->
    <div v-if="issues.length > 0" class="issues-bar">
      <div
        v-for="(issue, i) in issues"
        :key="i"
        :class="['issue-item', issue.level === 'ERROR' ? 'issue--error' : 'issue--warn']"
      >
        [{{ issue.level }}] {{ issue.field }}: {{ issue.message }}
      </div>
    </div>

    <!-- 主内容：双栏 -->
    <div class="editor-body">
      <!-- 左侧 -->
      <div class="editor-left">
        <div class="left-scroll">
          <!-- 基本信息 -->
          <div class="section">
            <h3 class="section-title">基本信息</h3>
            <div class="form-field">
              <label class="field-label">任务编码</label>
              <el-input
                v-model="task.taskCode"
                :disabled="readOnly || !!persistedCode"
                placeholder="如: create_test_data"
                size="small"
                class="mono-input"
              />
            </div>
            <div class="form-field">
              <label class="field-label">任务名称</label>
              <el-input
                v-model="task.taskName"
                :disabled="readOnly"
                placeholder="如: 电商测试数据生成"
                size="small"
              />
            </div>
            <div class="form-field">
              <label class="field-label">备注</label>
              <el-input
                v-model="task.taskRemark"
                :disabled="readOnly"
                type="textarea"
                :rows="3"
                placeholder="任务说明..."
                size="small"
              />
            </div>
          </div>

          <!-- 步骤列表 -->
          <div class="section">
            <div class="section-header">
              <h3 class="section-title">场景步骤</h3>
              <el-button v-if="!readOnly" size="mini" plain @click="addStep">
                <font-awesome-icon icon="plus" /> 添加步骤
              </el-button>
            </div>

            <div v-if="task.steps.length === 0" class="empty-steps">
              暂无步骤，点击"添加步骤"编排场景
            </div>

            <div v-else class="step-list">
              <div
                v-for="(step, idx) in task.steps"
                :key="step.stepId"
                :class="['step-item', { 'step-item--active': selectedStepId === step.stepId }]"
                @click="selectedStepId = step.stepId"
              >
                <span class="step-idx">{{ idx + 1 }}</span>
                <div class="step-info">
                  <div class="step-name">{{ step.stepName || step.stepId }}</div>
                  <div class="step-scene">{{ sceneNameByCode(step.sceneCode) }}</div>
                </div>
                <el-switch
                  v-model="step.enabled"
                  :disabled="readOnly"
                  @click.native.stop
                />
              </div>
            </div>
          </div>

          <!-- 版本历史 -->
          <div v-if="versions.length > 0" class="section">
            <el-collapse>
              <el-collapse-item :title="`版本历史 (${versions.length})`">
                <div v-for="v in versions" :key="v.id" class="version-item">
                  <el-tag :type="v.versionStatus === 'PUBLISHED' ? '' : 'info'" size="mini">
                    v{{ v.versionNo }}
                  </el-tag>
                  <span class="version-status">{{ v.versionStatus }}</span>
                  <span class="version-time">{{ formatDate(v.createdAt) }}</span>
                </div>
              </el-collapse-item>
            </el-collapse>
          </div>
        </div>
      </div>

      <!-- 右侧 -->
      <div class="editor-right">
        <div v-if="selectedStep" class="step-detail">
          <div class="detail-scroll">
            <!-- 步骤基本信息 -->
            <div class="section">
              <h3 class="section-title">步骤配置</h3>
              <div class="detail-grid">
                <div class="form-field">
                  <label class="field-label">步骤 ID</label>
                  <el-input
                    :value="selectedStep.stepId"
                    :disabled="readOnly"
                    size="small"
                    class="mono-input"
                    @input="onStepFieldChange('stepId', $event)"
                  />
                </div>
                <div class="form-field">
                  <label class="field-label">步骤名称</label>
                  <el-input
                    :value="selectedStep.stepName || ''"
                    :disabled="readOnly"
                    size="small"
                    @input="onStepFieldChange('stepName', $event)"
                  />
                </div>
              </div>
            </div>

            <!-- 场景选择 -->
            <div class="section">
              <h3 class="section-title">关联场景</h3>
              <el-select
                :value="selectedStep.sceneCode || ''"
                :disabled="readOnly"
                placeholder="选择要执行的场景..."
                size="small"
                filterable
                style="width: 100%"
                @input="onStepFieldChange('sceneCode', $event)"
              >
                <el-option
                  v-for="sc in publishedScenes"
                  :key="sc.sceneCode"
                  :label="sc.sceneName + ' (' + sc.sceneCode + ')'"
                  :value="sc.sceneCode"
                />
              </el-select>
              <p v-if="selectedStep.sceneCode" class="scene-hint">
                运行时将执行场景 "{{ selectedStep.sceneCode }}" 的已发布版本。
              </p>
            </div>

            <!-- 依赖步骤 -->
            <div class="section">
              <h3 class="section-title">依赖步骤</h3>
              <div v-if="availableSteps.length > 0" class="dep-tags">
                <button
                  v-for="s in availableSteps"
                  :key="s.stepId"
                  :class="['dep-tag', { 'dep-tag--active': selectedStep.dependsOn.includes(s.stepId) }]"
                  :disabled="readOnly"
                  @click="toggleDependsOn(s.stepId)"
                >
                  {{ s.stepName || s.stepId }}
                </button>
              </div>
              <p v-else class="empty-hint">无其他步骤可依赖</p>
            </div>

            <!-- 参数映射 -->
            <div class="section">
              <el-collapse v-model="mappingOpen">
                <el-collapse-item title="参数映射">
                  <div class="form-field">
                    <label class="field-label">输入映射 (JSON)</label>
                    <p class="field-hint">任务变量 → 场景输入参数的映射</p>
                    <el-input
                      type="textarea"
                      :rows="6"
                      :disabled="readOnly"
                      :value="jsonStringify(selectedStep.inputMapping)"
                      class="mono-textarea"
                      @input="onInputMappingChange"
                    />
                  </div>
                  <div class="form-field">
                    <label class="field-label">输出映射 (JSON)</label>
                    <p class="field-hint">场景输出 → 任务变量的映射</p>
                    <el-input
                      type="textarea"
                      :rows="4"
                      :disabled="readOnly"
                      :value="jsonStringify(selectedStep.outputMapping)"
                      class="mono-textarea"
                      @input="onOutputMappingChange"
                    />
                  </div>
                </el-collapse-item>
              </el-collapse>
            </div>

            <!-- 删除 -->
            <div v-if="!readOnly" class="section section--border-top">
              <el-button type="danger" size="small" @click="removeStep(selectedStep.stepId)">
                <font-awesome-icon icon="trash" /> 删除此步骤
              </el-button>
            </div>
          </div>
        </div>
        <div v-else class="no-selection">
          选择左侧步骤进行配置，或添加新步骤
        </div>
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import Vue from 'vue'

import {
  createTask,
  getTask,
  listScenes,
  listTaskVersions,
  publishTask,
  updateTask,
  validateTask,
} from '@/datagen/common/lib/api'
import { createDefaultTask } from '@/datagen/common/lib/defaults'
import type {
  SceneSummary,
  TaskDefinition,
  TaskStepDefinition,
  TaskValidationIssue,
  TaskVersion,
} from '@/datagen/common/lib/types'

/**
 * 造数任务编辑器。
 * 从 React TaskEditor 跨框架重写为 Vue 2 + Element UI。
 * 支持新增、编辑、只读三种模式（由路由决定）。
 */
export default Vue.extend({
  name: 'TaskEditor',
  data() {
    return {
      task: createDefaultTask() as TaskDefinition,
      persistedCode: null as string | null,
      saving: false,
      publishing: false,
      validating: false,
      loading: false,
      issues: [] as TaskValidationIssue[],
      scenes: [] as SceneSummary[],
      versions: [] as TaskVersion[],
      selectedStepId: null as string | null,
      mappingOpen: ['mapping'],
    }
  },
  computed: {
    readOnly(): boolean {
      return this.$route.path.includes('/view/')
    },
    taskCode(): string {
      return (this.$route.params.code as string) || ''
    },
    headerTitle(): string {
      if (!this.persistedCode) return '新增任务'
      return this.readOnly ? '查看任务' : '编辑任务'
    },
    selectedStep(): TaskStepDefinition | null {
      if (!this.selectedStepId) return null
      return this.task.steps.find((s) => s.stepId === this.selectedStepId) ?? null
    },
    publishedScenes(): SceneSummary[] {
      return this.scenes.filter((s) => s.status === 'PUBLISHED')
    },
    availableSteps(): TaskStepDefinition[] {
      return this.task.steps.filter((s) => s.stepId !== this.selectedStepId)
    },
  },
  created() {
    if (this.taskCode) {
      this.loading = true
      getTask(this.taskCode)
        .then((data) => {
          this.task = this.normalizeTask(data)
          this.persistedCode = this.taskCode
        })
        .catch((err) => {
          this.$message.error(err instanceof Error ? err.message : '加载失败')
          this.goBack()
        })
        .finally(() => { this.loading = false })
    }
    listScenes({ limit: 500 })
      .then((result) => { this.scenes = result })
      .catch(() => { this.$message.error('加载场景列表失败') })
    if (this.taskCode) {
      listTaskVersions(this.taskCode)
        .then((v) => { this.versions = v })
        .catch(() => {})
    }
  },
  methods: {
    goBack() {
      this.$router.push('/datagen/tasks').catch(() => {})
    },
    sceneNameByCode(code: string): string {
      const scene = this.scenes.find((s) => s.sceneCode === code)
      return scene ? scene.sceneName : code || '未选择场景'
    },
    async save(showToast = true): Promise<string | null> {
      if (this.readOnly) return this.persistedCode
      if (!this.task.taskCode || !this.task.taskName) {
        if (showToast) this.$message.error('请先填写任务编码和名称')
        return null
      }
      this.saving = true
      try {
        const version = this.persistedCode
          ? await updateTask(this.persistedCode, this.task)
          : await createTask(this.task)
        this.task = this.normalizeTask(version.definition)
        this.persistedCode = version.taskCode
        if (showToast) this.$message.success(`已保存 (v${version.versionNo})`)
        return version.taskCode
      } catch (error) {
        if (showToast) this.$message.error(error instanceof Error ? error.message : '保存失败')
        return null
      } finally {
        this.saving = false
      }
    },
    async handleValidate() {
      const code = this.persistedCode ?? (await this.save(false))
      if (!code) return
      this.validating = true
      try {
        const result = await validateTask(code)
        this.issues = result.issues
        if (result.valid) {
          this.$message.success('校验通过')
        } else {
          this.$message.warning(`校验发现 ${result.issues.length} 个问题`)
        }
      } catch (error) {
        this.$message.error(error instanceof Error ? error.message : '校验失败')
      } finally {
        this.validating = false
      }
    },
    async handlePublish() {
      const code = this.persistedCode ?? (await this.save(false))
      if (!code) return
      this.publishing = true
      try {
        const version = await publishTask(code)
        this.task = this.normalizeTask(version.definition)
        this.$message.success(`已发布 v${version.versionNo}`)
        this.goBack()
      } catch (error) {
        this.$message.error(error instanceof Error ? error.message : '发布失败')
      } finally {
        this.publishing = false
      }
    },
    openRunDialog() {
      if (this.persistedCode) {
        this.$router.push(`/datagen/task/run/${encodeURIComponent(this.persistedCode)}`).catch(() => {})
      }
    },
    addStep() {
      if (this.readOnly) return
      const idx = this.task.steps.length
      const newStep: TaskStepDefinition = {
        stepId: `scene_step_${idx + 1}`,
        sceneCode: '',
        stepName: `步骤 ${idx + 1}`,
        enabled: true,
        dependsOn: [],
        inputMapping: {},
        outputMapping: {},
      }
      this.task = { ...this.task, steps: [...this.task.steps, newStep] }
      this.selectedStepId = newStep.stepId
    },
    removeStep(stepId: string) {
      if (this.readOnly) return
      this.task = {
        ...this.task,
        steps: this.task.steps.filter((s) => s.stepId !== stepId),
      }
      if (this.selectedStepId === stepId) this.selectedStepId = null
    },
    updateStep(updated: TaskStepDefinition) {
      this.task = {
        ...this.task,
        steps: this.task.steps.map((s) => (s.stepId === updated.stepId ? updated : s)),
      }
    },
    onStepFieldChange(field: string, value: string) {
      if (!this.selectedStep || this.readOnly) return
      this.updateStep({ ...this.selectedStep, [field]: value })
    },
    toggleDependsOn(stepId: string) {
      if (!this.selectedStep || this.readOnly) return
      const deps = this.selectedStep.dependsOn
      const next = deps.includes(stepId)
        ? deps.filter((id) => id !== stepId)
        : [...deps, stepId]
      this.updateStep({ ...this.selectedStep, dependsOn: next })
    },
    onInputMappingChange(value: string) {
      if (!this.selectedStep || this.readOnly) return
      try {
        this.updateStep({ ...this.selectedStep, inputMapping: JSON.parse(value) })
      } catch { /* 忽略无效 JSON */ }
    },
    onOutputMappingChange(value: string) {
      if (!this.selectedStep || this.readOnly) return
      try {
        this.updateStep({ ...this.selectedStep, outputMapping: JSON.parse(value) })
      } catch { /* 忽略无效 JSON */ }
    },
    jsonStringify(value: unknown): string {
      try { return JSON.stringify(value, null, 2) }
      catch { return '{}' }
    },
    normalizeTask(task: TaskDefinition): TaskDefinition {
      return {
        ...task,
        inputSchema: task.inputSchema || [],
        steps: (task.steps || []).map((s) => ({
          ...s,
          dependsOn: s.dependsOn || [],
          enabled: s.enabled ?? true,
          inputMapping: s.inputMapping || {},
          outputMapping: s.outputMapping || {},
        })),
        resultMapping: task.resultMapping || {},
      }
    },
    formatDate(value: string): string {
      if (!value) return '-'
      const d = new Date(value)
      return Number.isNaN(d.getTime()) ? value : d.toLocaleString()
    },
  },
})
</script>

<style scoped>
.task-editor {
  display: flex;
  flex-direction: column;
  height: 100%;
  background: var(--background);
}

.editor-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  border-bottom: 1px solid var(--border);
  padding: 8px 24px;
  flex-shrink: 0;
}

.header-left {
  display: flex;
  align-items: center;
  gap: 12px;
}

.header-title {
  margin: 0;
  font-size: 18px;
  font-weight: 600;
  color: var(--foreground);
}

.header-sub {
  margin: 2px 0 0;
  font-size: 12px;
  color: var(--muted-foreground);
}

.header-code {
  font-family: ui-monospace, SFMono-Regular, Menlo, monospace;
}

.header-actions {
  display: flex;
  gap: 8px;
  align-items: center;
}

.play-icon {
  color: #16a34a;
}

.issues-bar {
  border-bottom: 1px solid var(--border);
  background: #fffbeb;
  padding: 8px 24px;
  flex-shrink: 0;
}

.issue-item {
  font-size: 12px;
  padding: 2px 0;
}

.issue--error {
  color: #dc2626;
}

.issue--warn {
  color: #d97706;
}

.editor-body {
  display: flex;
  flex: 1;
  min-height: 0;
}

.editor-left {
  width: 360px;
  border-right: 1px solid var(--border);
  flex-shrink: 0;
}

.left-scroll {
  height: 100%;
  overflow-y: auto;
  padding: 16px;
}

.editor-right {
  flex: 1;
  min-width: 0;
}

.section {
  margin-bottom: 16px;
}

.section--border-top {
  border-top: 1px solid var(--border);
  padding-top: 16px;
}

.section-title {
  margin: 0 0 12px;
  font-size: 14px;
  font-weight: 600;
  color: var(--foreground);
}

.section-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  margin-bottom: 8px;
}

.section-header .section-title {
  margin: 0;
}

.form-field {
  margin-bottom: 12px;
}

.field-label {
  display: block;
  font-size: 12px;
  font-weight: 500;
  color: var(--muted-foreground);
  margin-bottom: 4px;
}

.field-hint {
  font-size: 10px;
  color: var(--muted-foreground);
  margin: 0 0 4px;
}

.mono-input >>> input {
  font-family: ui-monospace, SFMono-Regular, Menlo, monospace;
  font-size: 12px;
}

.mono-textarea >>> textarea {
  font-family: ui-monospace, SFMono-Regular, Menlo, monospace;
  font-size: 12px;
}

.empty-steps {
  border: 1px dashed var(--border);
  border-radius: 6px;
  padding: 16px;
  text-align: center;
  font-size: 12px;
  color: var(--muted-foreground);
}

.step-list {
  display: flex;
  flex-direction: column;
  gap: 4px;
}

.step-item {
  display: flex;
  align-items: center;
  gap: 8px;
  border: 1px solid var(--border);
  border-radius: 6px;
  padding: 8px;
  cursor: pointer;
  transition: background 0.15s;
  font-size: 12px;
}

.step-item:hover {
  background: var(--accent);
}

.step-item--active {
  border-color: var(--primary);
  background: rgba(59, 130, 246, 0.05);
}

.step-idx {
  font-family: ui-monospace, SFMono-Regular, Menlo, monospace;
  color: var(--muted-foreground);
  width: 20px;
  text-align: center;
  flex-shrink: 0;
}

.step-info {
  flex: 1;
  min-width: 0;
}

.step-name {
  font-weight: 500;
  color: var(--foreground);
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.step-scene {
  font-size: 10px;
  color: var(--muted-foreground);
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.version-item {
  display: flex;
  align-items: center;
  gap: 8px;
  font-size: 10px;
  color: var(--muted-foreground);
  padding: 2px 0;
}

.version-status {
  font-size: 10px;
}

.version-time {
  font-size: 10px;
}

.step-detail {
  height: 100%;
}

.detail-scroll {
  height: 100%;
  overflow-y: auto;
  padding: 24px;
  max-width: 720px;
}

.detail-grid {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 12px;
}

.scene-hint {
  font-size: 12px;
  color: var(--muted-foreground);
  margin: 8px 0 0;
}

.dep-tags {
  display: flex;
  flex-wrap: wrap;
  gap: 8px;
}

.dep-tag {
  border: 1px solid var(--border);
  border-radius: 6px;
  padding: 4px 8px;
  font-size: 12px;
  cursor: pointer;
  transition: all 0.15s;
  background: var(--card);
  color: var(--foreground);
}

.dep-tag:hover {
  background: var(--accent);
}

.dep-tag--active {
  border-color: var(--primary);
  background: rgba(59, 130, 246, 0.1);
  color: var(--primary);
}

.dep-tag:disabled {
  opacity: 0.5;
  cursor: not-allowed;
}

.empty-hint {
  font-size: 12px;
  color: var(--muted-foreground);
  font-style: italic;
  margin: 0;
}

.no-selection {
  display: flex;
  align-items: center;
  justify-content: center;
  height: 100%;
  color: var(--muted-foreground);
  font-size: 14px;
}
</style>

// frontend/src/gdp/datagen/task/task-editor.tsx
"use client";

import {
  ArrowLeftIcon,
  ChevronDownIcon,
  ChevronRightIcon,
  Loader2Icon,
  PlayIcon,
  PlusIcon,
  SaveIcon,
  SendIcon,
  Trash2Icon,
} from "lucide-react";
import { useEffect, useState } from "react";
import { toast } from "sonner";

import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import {
  Collapsible,
  CollapsibleContent,
  CollapsibleTrigger,
} from "@/components/ui/collapsible";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { ScrollArea } from "@/components/ui/scroll-area";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Switch } from "@/components/ui/switch";
import { Textarea } from "@/components/ui/textarea";
import { cn } from "@/lib/utils";

import {
  createTask,
  getTask,
  listScenes,
  listTaskVersions,
  publishTask,
  updateTask,
  validateTask,
} from "../common/lib/api";
import { createDefaultTask } from "../common/lib/defaults";
import type {
  SceneSummary,
  TaskDefinition,
  TaskStepDefinition,
  TaskValidationIssue,
  TaskVersion,
} from "../common/lib/types";

interface TaskEditorProps {
  taskCode?: string | null;
  onBack: () => void;
  readOnly?: boolean;
  onRun?: (taskCode: string) => void;
}

export function TaskEditor({ taskCode, onBack, readOnly, onRun }: TaskEditorProps) {
  const [task, setTask] = useState<TaskDefinition>(() => createDefaultTask());
  const [persistedCode, setPersistedCode] = useState<string | null>(taskCode ?? null);
  const [saving, setSaving] = useState(false);
  const [publishing, setPublishing] = useState(false);
  const [validating, setValidating] = useState(false);
  const [loading, setLoading] = useState(!!taskCode);
  const [issues, setIssues] = useState<TaskValidationIssue[]>([]);
  const [scenes, setScenes] = useState<SceneSummary[]>([]);
  const [versions, setVersions] = useState<TaskVersion[]>([]);
  const [selectedStepId, setSelectedStepId] = useState<string | null>(null);

  // Load task data
  useEffect(() => {
    if (taskCode) {
      setLoading(true);
      getTask(taskCode)
        .then((data) => {
          setTask(normalizeTask(data));
          setPersistedCode(taskCode);
        })
        .catch((err) => {
          toast.error(err instanceof Error ? err.message : "加载失败");
          onBack();
        })
        .finally(() => setLoading(false));
    } else {
      setTask(createDefaultTask());
      setPersistedCode(null);
    }
  }, [taskCode, onBack]);

  // Load available scenes
  useEffect(() => {
    listScenes({ limit: 500 })
      .then((s) => setScenes(s.filter((sc) => sc.status === "PUBLISHED")))
      .catch(() => toast.error("加载场景列表失败"));
  }, []);

  // Load versions
  useEffect(() => {
    if (persistedCode) {
      listTaskVersions(persistedCode)
        .then(setVersions)
        .catch(() => {});
    }
  }, [persistedCode]);

  const save = async (showToast = true): Promise<string | null> => {
    if (readOnly) return persistedCode;
    if (!task.taskCode || !task.taskName) {
      if (showToast) toast.error("请先填写任务编码和名称");
      return null;
    }
    setSaving(true);
    try {
      const version = persistedCode
        ? await updateTask(persistedCode, task)
        : await createTask(task);
      setTask(normalizeTask(version.definition));
      setPersistedCode(version.taskCode);
      if (showToast) toast.success(`已保存 (v${version.versionNo})`);
      return version.taskCode;
    } catch (error) {
      if (showToast) toast.error(error instanceof Error ? error.message : "保存失败");
      return null;
    } finally {
      setSaving(false);
    }
  };

  const handleValidate = async () => {
    const code = persistedCode ?? (await save(false));
    if (!code) return;
    setValidating(true);
    try {
      const result = await validateTask(code);
      setIssues(result.issues);
      if (result.valid) {
        toast.success("校验通过");
      } else {
        toast.warning(`校验发现 ${result.issues.length} 个问题`);
      }
    } catch (error) {
      toast.error(error instanceof Error ? error.message : "校验失败");
    } finally {
      setValidating(false);
    }
  };

  const handlePublish = async () => {
    const code = persistedCode ?? (await save(false));
    if (!code) return;

    setPublishing(true);
    try {
      const version = await publishTask(code);
      setTask(normalizeTask(version.definition));
      toast.success(`已发布 v${version.versionNo}`);
      onBack();
    } catch (error) {
      toast.error(error instanceof Error ? error.message : "发布失败");
    } finally {
      setPublishing(false);
    }
  };

  const addStep = () => {
    if (readOnly) return;
    const idx = task.steps.length;
    const newStep: TaskStepDefinition = {
      stepId: `scene_step_${idx + 1}`,
      sceneCode: "",
      stepName: `步骤 ${idx + 1}`,
      enabled: true,
      dependsOn: [],
      inputMapping: {},
      outputMapping: {},
    };
    setTask({ ...task, steps: [...task.steps, newStep] });
    setSelectedStepId(newStep.stepId);
  };

  const removeStep = (stepId: string) => {
    if (readOnly) return;
    setTask({
      ...task,
      steps: task.steps.filter((s) => s.stepId !== stepId),
    });
    if (selectedStepId === stepId) setSelectedStepId(null);
  };

  const updateStep = (updated: TaskStepDefinition) => {
    setTask({
      ...task,
      steps: task.steps.map((s) => (s.stepId === updated.stepId ? updated : s)),
    });
  };

  const selectedStep = task.steps.find((s) => s.stepId === selectedStepId) ?? null;

  if (loading) {
    return (
      <div className="flex h-full items-center justify-center">
        <Loader2Icon className="text-primary size-8 animate-spin" />
      </div>
    );
  }

  return (
    <div className="flex h-full flex-col">
      {/* Header */}
      <div className="flex items-center justify-between border-b px-6 py-3">
        <div className="flex items-center gap-3">
          <Button variant="ghost" size="icon" onClick={onBack}>
            <ArrowLeftIcon className="size-4" />
          </Button>
          <div>
            <h2 className="text-lg font-semibold">
              {persistedCode ? (readOnly ? "查看任务" : "编辑任务") : "新增任务"}
            </h2>
            <p className="text-xs text-muted-foreground">
              {task.taskName || "未命名任务"}
              {persistedCode && ` (${persistedCode})`}
            </p>
          </div>
        </div>
        <div className="flex items-center gap-2">
          {persistedCode && task.status === "PUBLISHED" && onRun && !readOnly && (
            <Button variant="outline" size="sm" onClick={() => onRun(persistedCode)} className="gap-1 text-green-600">
              <PlayIcon className="size-3.5" /> 执行
            </Button>
          )}
          {!readOnly && (
            <>
              <Button variant="outline" size="sm" onClick={handleValidate} disabled={validating} className="gap-1">
                {validating ? <Loader2Icon className="size-3.5 animate-spin" /> : null}
                校验
              </Button>
              <Button variant="outline" size="sm" onClick={() => save()} disabled={saving} className="gap-1">
                {saving ? <Loader2Icon className="size-3.5 animate-spin" /> : <SaveIcon className="size-3.5" />}
                保存
              </Button>
              <Button size="sm" onClick={handlePublish} disabled={publishing} className="gap-1">
                {publishing ? <Loader2Icon className="size-3.5 animate-spin" /> : <SendIcon className="size-3.5" />}
                发布
              </Button>
            </>
          )}
        </div>
      </div>

      {/* Validation issues */}
      {issues.length > 0 && (
        <div className="border-b bg-yellow-50 px-6 py-2">
          {issues.map((issue, i) => (
            <div key={i} className={cn("text-xs", issue.level === "ERROR" ? "text-red-600" : "text-yellow-600")}>
              [{issue.level}] {issue.field}: {issue.message}
            </div>
          ))}
        </div>
      )}

      {/* Main content: two-column layout */}
      <div className="flex flex-1 min-h-0">
        {/* Left: basic info + step list */}
        <div className="w-[360px] border-r flex flex-col">
          <ScrollArea className="flex-1">
            <div className="p-4 space-y-4">
              {/* Basic info */}
              <div className="space-y-3">
                <h3 className="text-sm font-semibold">基本信息</h3>
                <div>
                  <Label className="text-xs">任务编码</Label>
                  <Input
                    value={task.taskCode}
                    disabled={readOnly || !!persistedCode}
                    onChange={(e) => setTask({ ...task, taskCode: e.target.value })}
                    placeholder="如: create_test_data"
                    className="h-8 font-mono text-xs"
                  />
                </div>
                <div>
                  <Label className="text-xs">任务名称</Label>
                  <Input
                    value={task.taskName}
                    disabled={readOnly}
                    onChange={(e) => setTask({ ...task, taskName: e.target.value })}
                    placeholder="如: 电商测试数据生成"
                    className="h-8 text-xs"
                  />
                </div>
                <div>
                  <Label className="text-xs">备注</Label>
                  <Textarea
                    value={task.taskRemark ?? ""}
                    disabled={readOnly}
                    onChange={(e) => setTask({ ...task, taskRemark: e.target.value })}
                    placeholder="任务说明..."
                    className="min-h-[60px] text-xs resize-none"
                  />
                </div>
              </div>

              {/* Step list */}
              <div className="space-y-2">
                <div className="flex items-center justify-between">
                  <h3 className="text-sm font-semibold">场景步骤</h3>
                  {!readOnly && (
                    <Button variant="outline" size="sm" onClick={addStep} className="h-7 text-xs gap-1">
                      <PlusIcon className="size-3" /> 添加步骤
                    </Button>
                  )}
                </div>

                {task.steps.length === 0 ? (
                  <div className="border border-dashed rounded-md p-4 text-center text-xs text-muted-foreground">
                    暂无步骤，点击"添加步骤"编排场景
                  </div>
                ) : (
                  <div className="space-y-1">
                    {task.steps.map((step, idx) => {
                      const scene = scenes.find((s) => s.sceneCode === step.sceneCode);
                      return (
                        <div
                          key={step.stepId}
                          className={cn(
                            "flex items-center gap-2 rounded-md border p-2 cursor-pointer transition-colors text-xs",
                            selectedStepId === step.stepId
                              ? "border-primary bg-primary/5"
                              : "hover:bg-muted"
                          )}
                          onClick={() => setSelectedStepId(step.stepId)}
                        >
                          <span className="font-mono text-muted-foreground w-5 text-center shrink-0">
                            {idx + 1}
                          </span>
                          <div className="flex-1 min-w-0">
                            <div className="font-medium truncate">
                              {step.stepName || step.stepId}
                            </div>
                            <div className="text-muted-foreground text-[10px] truncate">
                              {scene ? scene.sceneName : step.sceneCode || "未选择场景"}
                            </div>
                          </div>
                          <Switch
                            checked={step.enabled}
                            disabled={readOnly}
                            onCheckedChange={(checked) =>
                              updateStep({ ...step, enabled: checked })
                            }
                            onClick={(e) => e.stopPropagation()}
                          />
                        </div>
                      );
                    })}
                  </div>
                )}
              </div>

              {/* Version history */}
              {versions.length > 0 && (
                <Collapsible>
                  <CollapsibleTrigger className="flex items-center gap-1 text-xs font-semibold text-muted-foreground">
                    <ChevronRightIcon className="size-3" />
                    版本历史 ({versions.length})
                  </CollapsibleTrigger>
                  <CollapsibleContent className="pt-2 space-y-1">
                    {versions.map((v) => (
                      <div key={v.id} className="text-[10px] text-muted-foreground flex items-center gap-2">
                        <Badge variant={v.versionStatus === "PUBLISHED" ? "default" : "secondary"} className="text-[9px] h-4 py-0">
                          v{v.versionNo}
                        </Badge>
                        <span>{v.versionStatus}</span>
                        <span>{new Date(v.createdAt).toLocaleString()}</span>
                      </div>
                    ))}
                  </CollapsibleContent>
                </Collapsible>
              )}
            </div>
          </ScrollArea>
        </div>

        {/* Right: selected step detail */}
        <div className="flex-1 min-w-0">
          {selectedStep ? (
            <StepDetailPanel
              step={selectedStep}
              scenes={scenes}
              allSteps={task.steps}
              onChange={updateStep}
              onDelete={removeStep}
              readOnly={readOnly}
            />
          ) : (
            <div className="flex h-full items-center justify-center text-muted-foreground text-sm">
              选择左侧步骤进行配置，或添加新步骤
            </div>
          )}
        </div>
      </div>
    </div>
  );
}

/* ── Step detail panel ──────────────────────────────────────────────── */

function StepDetailPanel({
  step,
  scenes,
  allSteps,
  onChange,
  onDelete,
  readOnly,
}: {
  step: TaskStepDefinition;
  scenes: SceneSummary[];
  allSteps: TaskStepDefinition[];
  onChange: (step: TaskStepDefinition) => void;
  onDelete: (stepId: string) => void;
  readOnly?: boolean;
}) {
  const [mappingOpen, setMappingOpen] = useState(true);
  const availableSteps = allSteps.filter((s) => s.stepId !== step.stepId);

  return (
    <ScrollArea className="h-full">
      <div className="p-6 space-y-6 max-w-3xl">
        {/* Step basic info */}
        <div className="space-y-3">
          <h3 className="text-sm font-semibold">步骤配置</h3>
          <div className="grid grid-cols-2 gap-3">
            <div>
              <Label className="text-xs">步骤 ID</Label>
              <Input
                value={step.stepId}
                disabled={readOnly}
                onChange={(e) => onChange({ ...step, stepId: e.target.value })}
                className="h-8 font-mono text-xs"
              />
            </div>
            <div>
              <Label className="text-xs">步骤名称</Label>
              <Input
                value={step.stepName ?? ""}
                disabled={readOnly}
                onChange={(e) => onChange({ ...step, stepName: e.target.value })}
                className="h-8 text-xs"
              />
            </div>
          </div>
        </div>

        {/* Scene selection */}
        <div className="space-y-3">
          <h3 className="text-sm font-semibold">关联场景</h3>
          <Select
            value={step.sceneCode || ""}
            onValueChange={(v) => onChange({ ...step, sceneCode: v })}
            disabled={readOnly}
          >
            <SelectTrigger className="text-xs">
              <SelectValue placeholder="选择要执行的场景..." />
            </SelectTrigger>
            <SelectContent>
              {scenes.map((sc) => (
                <SelectItem key={sc.sceneCode} value={sc.sceneCode}>
                  {sc.sceneName} ({sc.sceneCode})
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
          {step.sceneCode && (
            <p className="text-xs text-muted-foreground">
              运行时将执行场景 "{step.sceneCode}" 的已发布版本。
            </p>
          )}
        </div>

        {/* Dependencies */}
        <div className="space-y-3">
          <h3 className="text-sm font-semibold">依赖步骤</h3>
          {availableSteps.length > 0 ? (
            <div className="flex flex-wrap gap-2">
              {availableSteps.map((s) => {
                const isSelected = step.dependsOn.includes(s.stepId);
                return (
                  <button
                    key={s.stepId}
                    disabled={readOnly}
                    onClick={() => {
                      const next = isSelected
                        ? step.dependsOn.filter((id) => id !== s.stepId)
                        : [...step.dependsOn, s.stepId];
                      onChange({ ...step, dependsOn: next });
                    }}
                    className={cn(
                      "rounded-md border px-2 py-1 text-xs transition-colors",
                      isSelected
                        ? "border-primary bg-primary/10 text-primary"
                        : "hover:bg-muted"
                    )}
                  >
                    {s.stepName || s.stepId}
                  </button>
                );
              })}
            </div>
          ) : (
            <p className="text-xs text-muted-foreground italic">无其他步骤可依赖</p>
          )}
        </div>

        {/* Input/Output mapping */}
        <Collapsible open={mappingOpen} onOpenChange={setMappingOpen}>
          <CollapsibleTrigger className="flex items-center gap-1 text-sm font-semibold">
            {mappingOpen ? <ChevronDownIcon className="size-4" /> : <ChevronRightIcon className="size-4" />}
            参数映射
          </CollapsibleTrigger>
          <CollapsibleContent className="pt-3 space-y-4">
            <div>
              <Label className="text-xs">输入映射 (JSON)</Label>
              <p className="text-[10px] text-muted-foreground mb-1">
                任务变量 → 场景输入参数的映射，如 {"{"} &quot;userId&quot;: &quot;$&#123;input.userId&#125;&quot; {"}"}
              </p>
              <Textarea
                className="font-mono text-xs"
                rows={6}
                disabled={readOnly}
                value={JSON.stringify(step.inputMapping, null, 2)}
                onChange={(e) => {
                  try { onChange({ ...step, inputMapping: JSON.parse(e.target.value) }); }
                  catch { /* ignore */ }
                }}
              />
            </div>
            <div>
              <Label className="text-xs">输出映射 (JSON)</Label>
              <p className="text-[10px] text-muted-foreground mb-1">
                场景输出 → 任务变量的映射，如 {"{"} &quot;orderNo&quot;: &quot;orderNo&quot; {"}"}
              </p>
              <Textarea
                className="font-mono text-xs"
                rows={4}
                disabled={readOnly}
                value={JSON.stringify(step.outputMapping, null, 2)}
                onChange={(e) => {
                  try { onChange({ ...step, outputMapping: JSON.parse(e.target.value) }); }
                  catch { /* ignore */ }
                }}
              />
            </div>
          </CollapsibleContent>
        </Collapsible>

        {/* Delete */}
        {!readOnly && (
          <div className="border-t pt-4">
            <Button variant="destructive" size="sm" onClick={() => onDelete(step.stepId)} className="gap-1 text-xs">
              <Trash2Icon className="size-3.5" /> 删除此步骤
            </Button>
          </div>
        )}
      </div>
    </ScrollArea>
  );
}

/* ── helpers ─────────────────────────────────────────────────────────── */

function normalizeTask(task: TaskDefinition): TaskDefinition {
  return {
    ...task,
    inputSchema: task.inputSchema || [],
    steps: (task.steps || []).map((s) => ({
      ...s,
      dependsOn: s.dependsOn || [],
      enabled: s.enabled ?? true,
      inputMapping: s.inputMapping || {},
      outputMapping: s.outputMapping || {},
    })),
    resultMapping: task.resultMapping || {},
  };
}
